[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
solc='0.8.19'

remappings = [
  'chainlink/=lib/chainlink/contracts/',
  'openzeppelin-contracts/=lib/aave-governance-v3/lib/openzeppelin-contracts/',
  'aave-governance-v3/=lib/aave-governance-v3/',
  'aave-address-book/=lib/aave-address-book/src/',
  'aave-delivery-infrastructure/=lib/aave-governance-v3/lib/aave-delivery-infrastructure/src/',
  'solidity-utils/=lib/aave-governance-v3/lib/solidity-utils/src/',
  'aave-token-v3/=lib/aave-governance-v3/lib/aave-token-v3/src/'
]
fs_permissions = [{access = "write", path = "./reports"}]
ffi = true

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
bnb = "${RPC_BNB}"
base = "${RPC_BASE}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
sepolia = "${RPC_SEPOLIA}"
goerli = "${RPC_GOERLI}"
fuji = "${RPC_FUJI}"
mumbai = "${RPC_MUMBAI}"
bnb_testnet = "${RPC_BNB_TESTNET}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chainId=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chainId=43114}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chainId=137}
base={key="${ETHERSCAN_API_KEY_BASE}",chain=8453}
mumbai={key="${ETHERSCAN_API_KEY_POLYGON}",chainId=80001}
bnb_testnet={key="${ETHERSCAN_API_KEY_BNB}",chainId=97, url='https://api-testnet.bscscan.com/'}
bnb={key="${ETHERSCAN_API_KEY_BNB}",chainId=56,url='https://api.bscscan.com/api'}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chainId=42161}
fantom={key="${ETHERSCAN_API_KEY_FANTOM}",chainId=250}
goerli={key="${ETHERSCAN_API_KEY_GOERLI}",chainId=5}
sepolia={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=11155111}
fuji={key="${ETHERSCAN_API_KEY_FUJI}",chainId=43113}

# See more config options https://github.com/gakonst/foundry/tree/master/config
