[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
solc='0.8.19'

remappings = [
  'chainlink/=lib/chainlink/contracts/',
  'openzeppelin-contracts/=lib/aave-governance-v3/lib/openzeppelin-contracts/',
  'aave-governance-v3/=lib/aave-governance-v3/',
  'aave-address-book/=lib/aave-address-book/src/',
  'aave-delivery-infrastructure/=lib/aave-governance-v3/lib/aave-delivery-infrastructure/src/',
  'solidity-utils/=lib/solidity-utils/src/',
  'aave-token-v3/=lib/aave-governance-v3/lib/aave-token-v3/src/',
  'aave-helpers/=lib/aave-helpers/src/'
]
fs_permissions = [{access = "write", path = "./reports"}]
ffi = true

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
zkevm = "${RPC_ZKEVM}"
gnosis = "${RPC_GNOSIS}"
bnb = "${RPC_BNB}"
scroll="${RPC_SCROLL}"

[etherscan]
mainnet = { key="${ETHERSCAN_API_KEY_MAINNET}", chain=1 }
optimism = { key="${ETHERSCAN_API_KEY_OPTIMISM}", chain=10 }
avalanche = { key="${ETHERSCAN_API_KEY_AVALANCHE}", chain=43114 }
polygon = { key="${ETHERSCAN_API_KEY_POLYGON}", chain=137 }
arbitrum = { key="${ETHERSCAN_API_KEY_ARBITRUM}", chain=42161 }
fantom = { key="${ETHERSCAN_API_KEY_FANTOM}", chain=250 }
metis = { key="any", chainId=1088, url='https://andromeda-explorer.metis.io/' }
base = { key="${ETHERSCAN_API_KEY_BASE}", chainId=8453 }
zkevm = { key="${ETHERSCAN_API_KEY_ZKEVM}", chainId=1101 }
gnosis = { key="${ETHERSCAN_API_KEY_GNOSIS}", chainId=100 }
bnb= { key="${ETHERSCAN_API_KEY_BNB}",chainId=56,url='https://api.bscscan.com/api'}
scroll={key="${ETHERSCAN_API_KEY_SCROLL}",chainId=534352}

# See more config options https://github.com/gakonst/foundry/tree/master/config
